const searchVideoList = 
[
    {
        videoId: 'awkkyBH2zEo',
        isOnlyChannelStat: false,
        durationSeconds: 207,
        dislikeCount: '68963',
        description:
            'LISA - LALISA\n\n내 뒷모습만 봐도 알잖아\n어두워질 때 분홍빛이나\n새하얀 조명이 날 깨우면\n번쩍번쩍 세상을 흔들어\n\n머리를 하얗게 비운채\n시끄런 감정은 태울래\nBurn burn burn\n그때 난 네 갈증을 해소할 샴페인\n\nSip sip 나를 들이켜\n그래 더 저 높이 내 body 받들어 \nWant you to ring the alarm\n세상에게 알려 내 이름에다 입맞춰\n\nSay Lalisa love me Lalisa love me \nCall me Lalisa love me Lalisa love me\n알잖아 attitude\n뭘 더 어쩌라구\nThe loudest in the room \n\nJust Say Lalisa love me Lalisa love me \nCall me Lalisa love me Lalisa love me\n알잖아 attitude\n뭘 더 어쩌라구\nThe loudest in the room \n\nBaby get the megaphone\nPut it on speaker\nI said I can’t hear you\nSo you need to speak up\nPut that shiz on stereo\nEveryone else on very low \n\nProtect it like a barrier\nPromise there’s nothing scarier\nThan me if anybody coming gunnin for my man\nGonna catch a case\nGun up in my hand\nBam bam bam\nHit after hit though\nRocks in my wrist so I call em the flintstones\n\nRing the alarm\n세상에게 알려 내 이름에다 입맞춰 \n\nSay Lalisa love me Lalisa love me\nCall me Lalisa love me Lalisa love me\n알잖아 attitude \n뭘 더 어쩌라구\nThe loudest in the room \n\nJust Say Lalisa love me Lalisa love me \nCall me Lalisa love me Lalisa love me\n알잖아 attitude \n뭘 더 어쩌라구\nThe loudest in the room \n\n누구와도 비교 못해 그래봤자 you gon’ still love me\nYou need some L.A.L.I.S.A\n\n지금 너의 두 눈 앞에 서있는 내 이름을 기억해\nLove you some L.A.L.I.S.A\n\nYou cannot see me 어떻게 하는지 다 보여줘도\n태국에서 한국 거쳐 여기까지 went for the throat\n\nBeing the greatest of all time ain’t fantasy\n새까만 핑크빛 왕관 belongs to we\n\nLalisa Lalisa Lalisa 하늘 위 당당해\nLalisa Lalisa Lalisa 저들은 날 원해 \nLalisa Lalisa Lalisa catch me if you can\nLalisa Lalisa Lalisa Lalisa Lalisa\n\nSay Lalisa love me Lalisa love me \nCall me Lalisa love me Lalisa love me\n알잖아 attitude \n뭘 더 어쩌라구\nThe loudest in the room\n\nJust Say Lalisa love me Lalisa love me\nCall me Lalisa love me Lalisa love me \n알잖아 attitude \n뭘 더 어쩌라구\nThe loudest in the room\n\n#LISA #리사 #BLACKPINK #블랙핑크 #FIRSTSINGLEALBUM #LALISA #MV #20210910_12amEST #20210910_1pmKST #OUTNOW #YG\n\nMore about BLACKPINK @\nhttp://www.blackpinkofficial.com/\nhttp://www.youtube.com/BLACKPINKOFFICIAL\nhttp://www.facebook.com/BLACKPINKOFFICIAL\nhttp://www.twitter.com/ygent_official\nhttp://www.instagram.com/BLACKPINKOFFICIAL',
        likeCount: '10250348',
        nations: ['KR'],
        title: "LISA - 'LALISA' M/V",
        forNotEmbeddable: true,
        duration: 'PT3M27S',
        isShorts: false,
        viewCount: '116424966',
        isAd: false,
        channelId: 'UCOmHUn--16B90oW2L6FRR3A',
        publishedAt: '2021-09-10T04:00:13Z',
        category1: '0.7796',
        searchDate: '2021-09-13',
        searchEpoch: 1631509802228,
        dailyViewCount: 20797202,
        tags: [
            'YG Entertainment',
            'YG',
            '와이지',
            'K-pop',
            'BLACKPINK',
            '블랙핑크',
            '블핑',
            '제니',
            '로제',
            '리사',
            '지수',
            'LISA',
            'JISOO',
            'JENNIE',
            'ROSÉ',
            'BLINK',
            '블링크',
            'LISA SOLO',
            'LALISA',
            'LISA TEASER',
            'LALISA MV',
            'LISA MV',
            'LISA SOLO MV',
            'LISA LALISA MV',
        ],
        commentCount: '2277613',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        thumbnails: 'https://i.ytimg.com/vi/awkkyBH2zEo/default.jpg',
        category: ['ENTN'],
        categoryProbs: [
            { category: 'ENTN', percent: '0.7796' },
            { category: 'MUSIC', percent: '0.2129' },
            { category: 'LIFE', percent: '0.0019' },
        ],
        favoriteCount: '0',
        isLive: true,
        channel: {
            subscriberCount: '66200000',
            dailyViewCount: 163342245,
            title: 'BLACKPINK',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLTat8_vr7h2i29n67lvNLMp1F-9Ch2ejFRlRzt0zQ=s800-c-k-c0x00ffffff-no-rj-mo',
            subscriberChange: 72413,
            channelId: 'UCOmHUn--16B90oW2L6FRR3A',
        },
    },
        {
        videoId: 'EaswWiwMVs8',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-23T08:59:54Z',
        durationSeconds: 199,
        dislikeCount: '31759',
        description:
            'Stray Kids(스트레이 키즈) "소리꾼" M/V\n\nStray Kids THE 2ND ALBUM "NOEASY"\niTunes & Apple Music: https://apple.co/3moxkm9\nSpotify: https://spoti.fi/3Djh3VR\n\nStray Kids Official YouTube: https://www.youtube.com/c/StrayKids\nStray Kids Official Facebook: https://www.facebook.com/JYPEStrayKids/\nStray Kids Official Instagram: https://www.instagram.com/realstraykids/\nStray Kids Official Twitter: https://twitter.com/Stray_Kids\nStray Kids Official Fan\'s: https://fans.jype.com/StrayKids\n\n#StrayKids #NOEASY #소리꾼\n#스트레이키즈\n#Thunderous\n#StrayKidsComeback\n#YouMakeStrayKidsStay',
        searchDate: '2021-09-13',
        likeCount: '2804925',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 1137387,
        title: 'Stray Kids "소리꾼" M/V',
        forNotEmbeddable: true,
        tags: [
            'JYP Entertainment',
            'JYP',
            '스트레이 키즈',
            'Stray Kids',
            'SKZ',
            '스키즈',
            '방찬',
            '리노',
            '창빈',
            '현진',
            '한',
            '필릭스',
            '승민',
            '아이엔',
            'BangChan',
            'LeeKnow',
            'Changbin',
            'Hyunjin',
            'HAN',
            'Felix',
            'Seungmin',
            'I.N',
            '이민호',
            '서창빈',
            '황현진',
            '한지성',
            '이용복',
            '김승민',
            '양정인',
            '소리꾼',
            'Thunderous',
            'NOEASY',
            '소리꾼 뮤비',
            '소리꾼 뮤직비디오',
            'Thunderous MV',
            'Thunderous music video',
            'noeasy mv',
            'noeasy music video',
            '스트레이키즈 뮤비',
            '스키즈 뮤비',
            'skz mv',
            'stray kids mv',
            '스키즈 소리꾼',
            '스트레이키즈 소리꾼',
            '스트레이키즈 뮤직비디오',
            '스키즈 뮤직비디오',
            'stray kids thunderous',
            'skz thunderous',
            'stray kids 소리꾼',
            'skz 소리꾼',
            '노이지',
            '스트레이키즈 노이지',
            'stray kids noeasy',
            'skz noeasy',
        ],
        commentCount: '1254601',
        duration: 'PT3M19S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '70660610',
        thumbnails: 'https://i.ytimg.com/vi/EaswWiwMVs8/default.jpg',
        category: ['ENTN'],
        isAd: false,
        channelId: 'UCaO6TYtlC8U5ttz62hTrZgg',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '22000000',
            dailyViewCount: 8725969,
            title: 'JYP Entertainment',
            thumbnails:
                'https://yt3.ggpht.com/fxlLUAZQPfYiK_6B-8ZQDbT1C_o-LkTTT75RO_JZ_78SbTSrNrRHB-X7nJkUJYKUb2XOos_Tnw=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 13793,
            channelId: 'UCaO6TYtlC8U5ttz62hTrZgg',
        },
    },
    {
        videoId: 'c9RzZpV460k',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-16T09:00:48Z',
        durationSeconds: 190,
        dislikeCount: '31366',
        description:
            "Red Velvet's 6th Mini Album \"Queendom\" is out!\nListen and download on your favorite platform: https://smarturl.it/RedVelvet_Queendom\n\n[Tracklist]\n01 Queendom\n02 Pose\n03 Knock On Wood \n04 Better Be\n05 Pushin’ N Pullin’\n06 다시, 여름 (Hello, Sunset)\n\nRed Velvet Official\nhttp://www.youtube.com/redvelvet\nhttp://www.facebook.com/RedVelvet\nhttp://www.instagram.com/redvelvet.smtown\nhttps://www.tiktok.com/@redvelvet_smtown\nhttps://www.vlive.tv/channel/DCF447\nhttp://twitter.com/RVsmtown\n\n#RedVelvet #레드벨벳 #Queendom #퀸덤\nRed Velvet 레드벨벳 'Queendom' MV ℗ SM Entertainment",
        searchDate: '2021-09-13',
        likeCount: '2284253',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 515445,
        title: "Red Velvet 레드벨벳 'Queendom' MV",
        forNotEmbeddable: true,
        commentCount: '240478',
        duration: 'PT3M10S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '63766186',
        thumbnails: 'https://i.ytimg.com/vi/c9RzZpV460k/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UCEf_Bc-KVd7onSeifS3py9g',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '28700000',
            dailyViewCount: 8259268,
            title: 'SMTOWN',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLSXEKHwjY8vsYiHiuythAqiZmKkktXucDF978zaow4=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 10344,
            channelId: 'UCEf_Bc-KVd7onSeifS3py9g',
        },
    },
    {
        videoId: 'ymaIzkXY8nQ',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-27T04:00:03Z',
        durationSeconds: 167,
        dislikeCount: '43419',
        description:
            "BTS (방탄소년단) 'Butter (feat. Megan Thee Stallion)' Official Visualizer\n\nCredits:\nBrand Experience Design: LONETONE, Suyeon Jung, Yennie, Yeeun Kim, Hyeri Lee, Seayol Choi\nMotion Graphic: HA&D\n\nBIGHIT MUSIC. Rights are reserved selectively in the video. Unauthorized reproduction is a violation of applicable laws. Manufactured by BIGHIT MUSIC, Seoul, Korea.\n\n\n\nConnect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://channels.vlive.tv/FE619 \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://i.youku.com/btsofficial \nhttp://btsblog.ibighit.com\n\n\n#BTS #방탄소년단 #BTS_Butter #MeganTheeStallion",
        searchDate: '2021-09-13',
        likeCount: '5006695',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 629171,
        title: "BTS (방탄소년단) 'Butter (feat. Megan Thee Stallion)' Official Visualizer",
        forNotEmbeddable: true,
        tags: ['HYBE', 'HYBE LABELS', '하이브', '하이브레이블즈'],
        commentCount: '619845',
        duration: 'PT2M47S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '39566055',
        thumbnails: 'https://i.ytimg.com/vi/ymaIzkXY8nQ/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '61200000',
            dailyViewCount: 18170747,
            title: 'HYBE LABELS',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLRPqF65CIc0pbXoyyY4xdFZQ7q9XMd1LPYxBoIQLg=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 34482,
            channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        },
    },
    {
        videoId: 'khGjK2Ml80Y',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-17T09:00:20Z',
        durationSeconds: 221,
        dislikeCount: '660',
        description:
            'CIX (씨아이엑스) - WAVE M/V\n\nCIX Fancafe ▶ http://cafe.daum.net/OfficialCIX\nCIX Official TWITTER ▶https://twitter.com/CIX_official\nCIX MEMBERS TWITTER ▶https://twitter.com/CIX_twt\nCIX Instagram ▶ https://www.instagram.com/cix.official/\nCIX Facebook ▶ https://www.facebook.com/CIXofficial/\nCIX V LIVE ▶https://channels.vlive.tv/B8D8CB/home\nCIX tiktok ▶ https://www.tiktok.com/@cix_official\nCIX Weibo ▶https://m.weibo.cn/u/7321086797\nCIX Douyin ▶https://bit.ly/2SGnEEr\n\n#CIX #씨아이엑스 #WAVE',
        searchDate: '2021-09-13',
        likeCount: '111794',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 103640,
        title: 'CIX (씨아이엑스) - WAVE M/V',
        forNotEmbeddable: true,
        commentCount: '20133',
        duration: 'PT3M41S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '24',
        viewCount: '29482382',
        thumbnails: 'https://i.ytimg.com/vi/khGjK2Ml80Y/default.jpg',
        category: ['LIFE'],
        isAd: false,
        channelId: 'UCuaslC77K-NmCy8Xwk7x0hA',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '747000',
            dailyViewCount: 119913,
            title: 'CIX Official',
            thumbnails:
                'https://yt3.ggpht.com/gz1hI6VGdr7Xg6yA7WuKdaDC7N3N2XjeIcny4prYy8CJhXmNADPB5Paqvtfh9z2sGGNOG1Ac=s800-c-k-c0x00ffffff-no-nd-rj',
            subscriberChange: 586,
            channelId: 'UCuaslC77K-NmCy8Xwk7x0hA',
        },
    },
    {
        videoId: 'K-0mbJGWA-k',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-23T09:00:04Z',
        durationSeconds: 267,
        dislikeCount: '1030',
        description:
            '#T1419​​​ 3rd Single Album [BEFORE SUNRISE Part. 3] #FLEX​ #MV\n\n☆T1419 Official Youtube\nhttps://youtube.com/c/T1419_official\n\n☆Official Twitter\nhttp://twitter.com/T1419_official​​​​\n\n☆Official Instagram\nhttp://instagram.com/t1419_official/​​​​\n\n☆Official Facebook\nhttps://facebook.com/T1419-108039604406260 \n\n☆Official Homepage\nhttp://www.mldenter.com​​​​\n\nMLD ENTERTAINMENT Official Youtube',
        searchDate: '2021-09-13',
        likeCount: '36098',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 730213,
        title: "T1419 3rd Single Album [BEFORE SUNRISE Part. 3] 'FLEX' M/V",
        forNotEmbeddable: true,
        tags: [
            'BAAM',
            '배엠',
            'MLD',
            '엠엘디',
            '엠엘디엔터테인먼트',
            'MLDENTERTAINMENT',
            '모모랜드',
            'MOMOLAND',
            '낸시',
            '주이',
            '연우',
            '혜빈',
            '나윤',
            '제인',
            '아인',
            'nancy',
            'jooe',
            'yeonwoo',
            'hyebin',
            'jane',
            'daisy',
            'ahin',
            'nayun',
            'taeha',
            '트로피카나',
            '뿜뿜',
            '그레잇',
            'great',
            'bboombboom',
            'dance',
            'edm',
            'kpop',
            '암쏘핫',
            "I'mSohot",
            'T1419',
            '드라큘라',
            'Dracula',
        ],
        commentCount: '10694',
        duration: 'PT4M27S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '24',
        viewCount: '25017771',
        thumbnails: 'https://i.ytimg.com/vi/K-0mbJGWA-k/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UC62GnXAfqgm8Fcn_i9kiuqw',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '1720000',
            dailyViewCount: 829609,
            title: 'MLD ENTERTAINMENT',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLTV7GftS9fVqtRGi6XqwRoxE9qh0KOSNOyC9vT5tg=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 689,
            channelId: 'UC62GnXAfqgm8Fcn_i9kiuqw',
        },
    },
    {
        videoId: 'JzODRUBBXpc',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-17T08:58:10Z',
        durationSeconds: 237,
        dislikeCount: '14545',
        description:
            "TXT (투모로우바이투게더) 'LO$ER=LO♡ER' Official MV\n\nCredits:\n\nDirector: Guzza (Lumpens)\n1st AD: Soeyoung Park\n2nd AD: Ran Ro (Lumpens)\nPA: Kookki Kim, Seongyeol Park, Chanyang Kim\n\nProducer: Emma Sungeun Kim (GE Production)\nLocation Manager: Juyoung An\nAssistant Producers: Jihoon Han, Minho Seo, Hyunmo Yang, Hyoseok Kim\n\nDirector of Photography: EumKo\nB Cam Operator : Sangwoo Yun\nFocus Puller : Sungju Min, Youngwoo Lee\n2nd AC : Eunil Lee, Eunki Kim\n3rd AC : Youngseo Park\nDIT: Yuntae Ko\n\nJimmy Jib: Dongjin Lee\n1st Assistant: Ho Jun Choi\n2nd Assistant: Jeong Hyun Yoo\n\nCamera Car: Geumho Woo\n\nGaffer: Doo Soo Choi\nLighting Crew: Jung Hwan Heo, Ban Seog Yeom, Yu Jin Jung, Gi Hyeon Lee, Won Ho Jung, Sang Jun Lee, Eui Jung Lee, Chung Ki Kim\n\nProduction designer, Art Director: Bona Kim, Jinsil Park (MU:E)\n1st: Yeri Kang (MU:E)\nAssistant Art team: Jieun Yoon, Ayeong Choi (MU:E)\nArt-team Manager: ilho Heo (MU:E)\n\nLED Virtual Production by VIT (ViveStudios Immersive Technology)\nLED Virtual Production Camera Assistant: Sang Kyu Park, Daniel Kang\nLED Virtual Production Gaffer: Jin Gwon Kim\n\nTechnocrane: Ki Tae Kim, Ji Yong Lee, Myung Jun Lee\n\nVFX: Vive Studios\n\nStunt Team: Ki-lim Kim, Min-hyeok Choi, Yoon-heon Jung\n\nSFX : Kyoungsoo Park (JUST)\nSFX Supervisor: Youngwoong Choi\nSFX Technician: Chanmin Lee, Taesik Sul\n\nBIGHIT MUSIC. Rights are reserved selectively in the video. Unauthorized reproduction is a violation of applicable laws. Manufactured by BIGHIT MUSIC, Seoul, Korea.\n\n\nConnect with TOMORROW X TOGETHER:\nhttps://ibighit.com/txt​\nhttps://twitter.com/TXT_bighit​\nhttps://twitter.com/TXT_members​\nhttps://www.facebook.com/TXT.bighit​\nhttps://www.instagram.com/txt_bighit​\nhttps://channels.vlive.tv/BA18A3​\nhttps://www.tiktok.com/@txt.bighitent​ \nhttps://weverse.onelink.me/qt3S/8e901222​\nhttps://www.weibo.com/TXTbighit​\nhttp://i.youku.com/txtbighit\n\n#TheChaosChapter #FIGHT_OR_ESCAPE #투모로우바이투게더 #TOMORROW_X_TOGETHER #TXT",
        searchDate: '2021-09-13',
        likeCount: '2459885',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 343932,
        title: "TXT (투모로우바이투게더) 'LO$ER=LO♡ER' Official MV",
        forNotEmbeddable: true,
        tags: [
            'HYBE',
            'HYBE LABELS',
            '하이브',
            '하이브레이블즈',
            'TXT',
            'TOMORROW X TOGETHER',
            '투모로우바이투게더',
            'TheChaosChapter',
            'FIGHT OR ESCAPE',
            'LO$ER=LO♡ER',
        ],
        commentCount: '279082',
        duration: 'PT3M57S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '24679857',
        thumbnails: 'https://i.ytimg.com/vi/JzODRUBBXpc/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        favoriteCount: '0',
        isLive: true,
        channel: {
            subscriberCount: '61200000',
            dailyViewCount: 18170747,
            title: 'HYBE LABELS',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLRPqF65CIc0pbXoyyY4xdFZQ7q9XMd1LPYxBoIQLg=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 34482,
            channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        },
    },
    {
        videoId: '08MCd75frA8',
        isOnlyChannelStat: false,
        durationSeconds: 15,
        dislikeCount: '30390',
        description:
            '✔ "LALISA" is available for Pre-Save now! | https://LALISA.lnk.to/LALISAPreSave\n\n#LISA #리사 #BLACKPINK #블랙핑크 #FIRSTSINGLEALBUM #LALISA #TITLE #LALISA #MV_TEASER #20210910_12amEST #20210910_1pmKST #RELEASE #YG',
        likeCount: '2519267',
        nations: ['KR'],
        title: "LISA - 'LALISA' M/V TEASER",
        forNotEmbeddable: true,
        duration: 'PT15S',
        viewCount: '23923935',
        isAd: false,
        channelId: 'UCOmHUn--16B90oW2L6FRR3A',
        publishedAt: '2021-09-07T15:00:01Z',
        category1: '0.8874',
        searchDate: '2021-09-13',
        searchEpoch: 1631509802228,
        dailyViewCount: 461889,
        tags: [
            'YG Entertainment',
            'YG',
            '와이지',
            'K-pop',
            'BLACKPINK',
            '블랙핑크',
            '블핑',
            '제니',
            '로제',
            '리사',
            '지수',
            'LISA',
            'JISOO',
            'JENNIE',
            'ROSÉ',
            'BLINK',
            '블링크',
            'LISA SOLO',
            'LALISA',
            'LISA TEASER',
        ],
        commentCount: '239600',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        thumbnails: 'https://i.ytimg.com/vi/08MCd75frA8/default.jpg',
        category: ['ENTN'],
        categoryProbs: [
            { category: 'ENTN', percent: '0.8874' },
            { category: 'MUSIC', percent: '0.1058' },
            { category: 'LIFE', percent: '0.0020' },
        ],
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '66200000',
            dailyViewCount: 163342245,
            title: 'BLACKPINK',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLTat8_vr7h2i29n67lvNLMp1F-9Ch2ejFRlRzt0zQ=s800-c-k-c0x00ffffff-no-rj-mo',
            subscriberChange: 72413,
            channelId: 'UCOmHUn--16B90oW2L6FRR3A',
        },
    },
    {
        videoId: 'IkeZX2hnoOk',
        isOnlyChannelStat: false,
        durationSeconds: 69,
        dislikeCount: '19220',
        description:
            'Connect with BTS: \nhttps://ibighit.com/bts \nhttp://twitter.com/BTS_bighit\nhttp://twitter.com/BTS_twt \nhttp://www.facebook.com/bangtan.official \nhttps://www.youtube.com/user/BANGTANTV \nhttp://instagram.com/BTS.bighitofficial \nhttps://channels.vlive.tv/FE619 \nhttps://www.tiktok.com/@bts_official_bighit\nhttps://weverse.onelink.me/qt3S/94808190\nhttps://www.weibo.com/BTSbighit\nhttps://www.weibo.com/BTSmembers \nhttp://i.youku.com/btsofficial \nhttp://btsblog.ibighit.com',
        likeCount: '3878440',
        nations: ['KR'],
        title: "BTS (방탄소년단) 'Butter (feat. Megan Thee Stallion)' Special Performance Video",
        forNotEmbeddable: true,
        duration: 'PT1M9S',
        isShorts: false,
        viewCount: '22759644',
        isAd: false,
        channelId: 'UCLkAepWjdylmXSltofFvsYQ',
        publishedAt: '2021-09-09T03:00:05Z',
        category1: '0.9976',
        searchDate: '2021-09-13',
        searchEpoch: 1631509802228,
        dailyViewCount: 2104385,
        tags: [
            '방탄소년단',
            'BTS',
            'BANGTAN',
            'HIPHOP',
            '알엠',
            'RM',
            '슈가',
            'SUGA',
            '제이홉',
            'jhope',
            '지민',
            'JIMIN',
            '정국',
            'JUNGKOOK',
            'JIN',
        ],
        commentCount: '207957',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        thumbnails: 'https://i.ytimg.com/vi/IkeZX2hnoOk/default.jpg',
        category: ['MUSIC'],
        categoryProbs: [
            { category: 'MUSIC', percent: '0.9976' },
            { category: 'ENTN', percent: '0.0009' },
            { category: 'LIFE', percent: '0.0002' },
        ],
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '57800000',
            dailyViewCount: 35974121,
            title: 'BANGTANTV',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLTk3oOlcaYmGbmB0WrrSJzI_hX4RxCr8x5mpKHuXQ=s800-c-k-c0x00ffffff-no-rj-mo',
            subscriberChange: 48275,
            channelId: 'UCLkAepWjdylmXSltofFvsYQ',
        },
    },
    {
        videoId: 'ZIZECe-55HY',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-22T07:52:16Z',
        durationSeconds: 219,
        description:
            '[ official Site ]\r\nBrave        http://bravesound.com\r\nTwitter       http://twitter.com/bravesound_\r\nfacebook   http://www.facebook.com/BraveEntertainment\r\nInstagram  http://instagram.com/braveent_official\r\nTVcast       http://tvcast.naver.com/bravesound\n\n#브레이브걸스 #AfterWeRide #술버릇 \n#BraveGirls #운전만해_그후\n#피어레스 #FEARLESS',
        searchDate: '2021-09-13',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 29354,
        title: '브레이브걸스(Brave Girls) - 술버릇 (운전만해 그후) MV',
        forNotEmbeddable: true,
        tags: [
            '브레이브엔터테인먼트',
            'Braveentertainment',
            '용감한형제',
            'Bravebrother',
            'Bravesound',
            '브레이브걸스',
            'Brave girls',
            '민영',
            '은지',
            '유나',
            '유정',
            'Minyoung',
            'Eunji',
            'Yuna',
            'Yujeong',
            'After We Ride',
            "After 'We Ride'",
            '술버릇',
            '술버릇 (운전만해 그후)',
            '롤린',
            "Rollin'",
            'We Ride',
            '운전만해',
            '하이힐',
            'High Heels',
            '브걸',
            '브브걸',
            '쁘걸',
            'KPOP',
        ],
        commentCount: '18287',
        duration: 'PT3M39S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '24',
        viewCount: '21616787',
        thumbnails: 'https://i.ytimg.com/vi/ZIZECe-55HY/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UCrhH1dPISpWYDA6h5XHE9sw',
        favoriteCount: '0',
        dislikeCount: '3150',
        likeCount: '193382',
        isLive: true,
        channel: {
            subscriberCount: '427000',
            dailyViewCount: 108513,
            title: 'Brave Entertainment',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLTzAvIRweJ6FF9wRUA66jB5BEA2LoT1xshAbMvxMA=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 620,
            channelId: 'UCrhH1dPISpWYDA6h5XHE9sw',
        },
    },
    {
        videoId: '1-rD_vr_2xQ',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-30T09:00:00Z',
        durationSeconds: 215,
        dislikeCount: '930',
        description:
            "비투비 (BTOB) - 'Outsider' Official Music Video\n\nComposed by 라이언 전, Cameron Warren, Max Cooke, Shaun Smith\nLyrics by 이민혁 (HUTA), 프니엘\nArranged by 라이언 전, Cameron Warren\n\n쳇바퀴 돌 듯 반복되는 일상 속에 지쳐가는 우리네 이야기.\n하루하루 버텨낸다, 견뎌낸다는 표현에 많은 이들이 공감할 것이다. 이런 세상에서 우린 가끔 ‘Outsider’가 되고 싶다. 흔히 사용되는 ‘Outsider’의 의미가 아닌 매일 똑같은 패턴과 삶에서 벗어나 자유로워지고 싶고, 내가 ‘나’다울 수 있게 강해지고 싶다는 의미를 담았다.\n\nThis is about the story of our life and how we get tired of repetitive daily life spinning like a wheel. \nThe usage of words like ‘bearing’ and ‘enduring’ establishes empathy from many people. In a world like this, sometimes we just want to be an ‘Outsider’. The term ‘Outsider’ in the song is used to describe the desire to escape from the repetitive pattern of life and set yourself free to be stronger and realize your self-worth.\n\nBTOB Official Youtube: https://www.youtube.com/officialbtob\nBTOB Official Facebook: https://www.facebook.com/BTOBofficial\nBTOB Official Twitter: https://twitter.com/officialbtob\nBTOB Official Instagram: https://instagram.com/cube_official_btob\nBTOB Official Weibo: http://weibo.com/cubebtob\nBTOB Official Fansite: https://www.united-cube.com\n\nⓒ All Rights Reserved CUBE Entertainment Inc.\n\n#비투비 #BTOB #Outsider",
        searchDate: '2021-09-13',
        likeCount: '156315',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 354874,
        title: "비투비 (BTOB) - 'Outsider' Official Music Video",
        forNotEmbeddable: true,
        tags: [
            'kpop',
            'btob',
            '비투비',
            '멜로디',
            '뮤직비디오',
            '뮤비',
            'movie',
            'musicvideo',
            '서은광',
            '이민혁',
            '이창섭',
            '프니엘',
            'melody',
        ],
        commentCount: '27656',
        duration: 'PT3M35S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '19743458',
        thumbnails: 'https://i.ytimg.com/vi/1-rD_vr_2xQ/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UCgB7A457ULlgm5c3948vr-w',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '1750000',
            dailyViewCount: 605494,
            title: 'BTOB 비투비 (Official YouTube Channel)',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLR9dn82odQ7QppltdwLjoybDd6XfSqf-Kui_y10Lg=s800-c-k-c0x00ffffff-no-rj-mo',
            subscriberChange: 1034,
            channelId: 'UCgB7A457ULlgm5c3948vr-w',
        },
    },
    {
        videoId: '9u7Z7kYr-es',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-25T09:00:04Z',
        durationSeconds: 236,
        dislikeCount: '329',
        description:
            '미래소년 (MIRAE)\nSplash - MIRAE 2nd Mini Album\n\nSplash | MUSIC VIDEO\n\n#미래소년 #MIRAE\n#MIRAE_Splash\n\n\n== MIRAE official ==\n\n▲ YouTube | https://www.youtube.com/c/MIRAEofficial\n▲ VLIVE | https://www.vlive.tv/channel/A4DB4B\n▲ Official Twitter | https://www.twitter.com/official_MIRAE\n▲ Member Twitter | https://www.twitter.com/members_MIRAE\n▲ Instagram | https://www.instagram.com/official__mirae\n▲ Facebook | https://www.facebook.com/officialMIRAE\n▲ Cafe | https://cafe.daum.net/officialMIRAE\n▲ TikTok | https://www.tiktok.com/@official_mirae',
        searchDate: '2021-09-13',
        likeCount: '52530',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 8191,
        title: '미래소년 (MIRAE) - Splash',
        forNotEmbeddable: true,
        tags: [
            'dspmedia',
            'mirae',
            'mirae official',
            'dsp n mirae',
            'dsp n',
            'mirae film',
            'lee jun hyuk',
            'jun hyuk',
            'lien',
            'shimada shouu',
            'yoo dou hyun',
            'dou hyun',
            'khael',
            'lee sang min',
            'sang min',
            'son dong pyo',
            'dong pyo',
            'park si young',
            'si young',
            'jang yu bin',
            'yu bin',
            '이준혁',
            '준혁',
            '리안',
            '시마다쇼',
            '유도현',
            '도현',
            '카엘',
            '이상민',
            '상민',
            '손동표',
            '동표',
            '박시영',
            '시영',
            '장유빈',
            '유빈',
            '디에스피미디어',
            '미래소년',
            'mirae splash',
            'splash',
            'splash mirae',
            '미래소년 스플래시',
            '스플래시',
            '미래소년 스플래쉬',
            '스플래쉬',
            'mirae comeback',
        ],
        commentCount: '6395',
        duration: 'PT3M56S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '24',
        viewCount: '19568103',
        thumbnails: 'https://i.ytimg.com/vi/9u7Z7kYr-es/default.jpg',
        category: ['FILM'],
        isAd: false,
        channelId: 'UC0QBW1zC_WKWe5dhenG1ZUA',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '305000',
            dailyViewCount: 16477,
            title: 'MIRAE',
            thumbnails:
                'https://yt3.ggpht.com/v4xj_RembS0PLjDUVsxWOxWOGJH0pJVNhWShtSm64TM2FBwYhpkUDrN6tpenNbnS4Ct_AWIRug=s800-c-k-c0x00ffffff-no-nd-rj',
            subscriberChange: 689,
            channelId: 'UC0QBW1zC_WKWe5dhenG1ZUA',
        },
    },
    {
        videoId: 'BjmmvBMXbSU',
        isOnlyChannelStat: false,
        categoryProb1: [
            { category: 'MUSIC', percent: '0.9973' },
            { category: 'ENTN', percent: '0.0009' },
            { category: 'TECH', percent: '0.0002' },
        ],
        durationSeconds: 255,
        dislikeCount: '10287',
        description:
            "fromis_9 (프로미스나인) 'Talk & Talk' Official MV \n\n지난 5월 두 번째 싱글 앨범 [9 WAY TICKET]으로 전 세계 팬들에게 특별한 여행의 추억을 선물하며 ‘리프레시 메이트’가 되어 준 프로미스나인이 ‘톡톡’ 튀는 청량 에너지를 가득 담은 신보로 여름에 이어 가을까지 완벽 접수한다.\n\n타이틀곡 ‘Talk & Talk’은 새로운 만남이 시작되는 시점의 두근거림을 경험해본 사람이라면 누구나 쉽게 공감할 수 있는 감정을 섬세하게 담아낸 곡으로 밤새도록 전화 통화를 이어가고 싶은 풋풋한 설렘을 ‘아무 말 파티’, ‘끝말잇기’에 비유해 재치 있게 풀어냈다.\n\nfromis_9, who became “travel mates” and presented special travel memories to fans around the world with their second single album 9 WAY TICKET in May, are ready to continue their one of a kind sparkling and refreshing energy well into the fall with their new single. \n“Talk & Talk” delicately captures the fluttering emotions that anyone who has experienced butterflies at the beginning of a new encounter can easily relate to. The track wittily compares the youthful excitement of longing to talk on the phone all night long to a ‘say anything challenge’ and ‘word relay.’\n\nCredits:\nPRODUCTION｜FANTAZYLAB\n\nDIRECTOR｜ZIYONG KIM\nPRODUCER｜SUYEON JO\n1ST AD｜YG SUN\n2ND AD｜MINKYUNG LEE\n\nDIRECTOR OF PHOTOGRAPHY｜INMO YUN @ATOD\n1ST AC｜JAEHWAN RYU \n2ND AC｜HYUNJI KIM\n3RD AC｜JAEDO LEE\nDIT｜JAEDEOK KIM\n\nGAFFER｜BORAM KIM @WATTLITE\n1ST ASSISTANT｜YUBIN OH\n2ND｜INHYEOK LEE\n3RD｜HEESUNG PARK \n4TH｜JUYOUNG JUNG \n5TH｜KYUNG YUP KIM \n\nART DIRECTOR｜HYE SUN SHIN @CINESON\nART TEAM LEADER｜DOEUN JUNG, YOUNG HEE SHIN\nART TEAM MEMBER｜EUNSEO CHOI, KWANGWON CHOI, CHAEWOON SON, WONJUN JANG\n\nJIMMY JIB｜DONGJIN LEE @JIMMYJIB MOTION\n1ST ASSISTANT｜HOJUN CHOI \n2ND ASSISTANT｜JEONGHYUN YOO \n\nEDIT｜ZIYONG KIM\n\nVFX｜YG SUN, VIKERS\n\nSOUND DIRECTOR｜ZIYONG KIM\nSFX DIRECTOR｜HYUNGSU CHAE @ASTRO\nSFX OPERATOR｜JUSUNG LEE \n\nDOG ACTOR｜PPUSYONG\n\nSTORYBOARD ARTIST｜SAM PARK\n\nPRODUCTION ASSISTANT｜SE EUNG JANG, JAE WOO SONG, SAEAM LEE, GONDRA, LUCY LEE\n \n#fromis_9 #프로미스나인\n#TalknTalk \n\nfromis_9 Official Homepage : https://www.pledis.co.kr/html/artist/fromisnine\nfromis_9 Official Twitter : https://twitter.com/realfromis_9\nfromis_9 Official Facebook : https://www.facebook.com/officialfromis9\nfromis_9 Official Instagram : https://www.instagram.com/officialfromis_9/\nfromis_9 Official Fancafe : https://cafe.daum.net/fromis9\n\nⓒ Pledis Entertainment. All Rights Reserved",
        likeCount: '407169',
        nations: ['KR'],
        title: "fromis_9 (프로미스나인) 'Talk & Talk' Official MV",
        forNotEmbeddable: true,
        duration: 'PT4M15S',
        viewCount: '18967685',
        isAd: false,
        channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        publishedAt: '2021-09-01T09:00:07Z',
        searchDate: '2021-09-13',
        searchEpoch: 1631509802228,
        dailyViewCount: 87593,
        tags: ['HYBE', 'HYBE LABELS', '하이브', '하이브레이블즈'],
        commentCount: '28894',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        thumbnails: 'https://i.ytimg.com/vi/BjmmvBMXbSU/default.jpg',
        category: ['MUSIC'],
        categoryProbs: [
            { category: 'MUSIC', percent: '0.9973' },
            { category: 'ENTN', percent: '0.0009' },
            { category: 'TECH', percent: '0.0002' },
        ],
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '61200000',
            dailyViewCount: 18170747,
            title: 'HYBE LABELS',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLRPqF65CIc0pbXoyyY4xdFZQ7q9XMd1LPYxBoIQLg=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 34482,
            channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        },
    },
    {
        videoId: 'EQwIC0424XQ',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-16T15:01:13Z',
        durationSeconds: 31,
        dislikeCount: '10',
        description:
            "우리 주변의 선한 생각들이 선한 영향력이 될 수 있도록,\nGoogle Play가 한국의 스타트업들과 함께 길을 열어갑니다.\n저희와 함께 이들의 선한 영향력이 더 전파될 수 있도록 함께해주세요!\n\n🥕당근마켓 | 다시 이웃과 가까워지는 정겨운 동네를 만들자는 생각 🏘️\n🦶🏻빅워크 | 걷는 것만으로도 좋은 일을 하게 하자는 생각 🙋‍♀️\n\n따뜻한 플레이가 더없이 많아지도록, Google Play \n\n👉 영상을 보시고 빅워크와 함께하는 구글플레이의 ‘따뜻한 플레이’ 기부 캠페인에도 참여해보세요! \n👉 빅워크 ‘따뜻한 플레이' 기부 캠페인 참여하기: https://bit.ly/3saQwVx",
        searchDate: '2021-09-13',
        likeCount: '82',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 664887,
        title: '선한 생각들이 선한 영향력이 될 수 있도록 ✨ | 당근마켓 🥕 | 빅워크 🦶 | Google Play 🚀',
        forNotEmbeddable: true,
        tags: [
            '구글플레이',
            '구글플레이 코리아',
            '구글',
            '구글 코리아',
            '구글플레이 스토어',
            '플레이 스토어',
            'Google Play',
            'Google Play Korea',
            'Google',
            'Google Korea',
            'Google Play Store',
            'Play store',
            '구글 앱',
            '구글 어플',
            '구글 모바일 앱',
            '구글 모바일 어플',
            '당근마켓',
            'daangn',
            '빅워크',
            'bigwalk',
            '오늘의분리수거',
            'oysterable',
            '포인핸드',
            'pawinhand',
            'Playon',
            'Play on Google',
            '중고거래',
            '인앱결제',
            '인앱결제 수수료',
            '구글수수료',
            '인앱 결제법안',
            '인앱결제금지',
        ],
        commentCount: '16',
        duration: 'PT31S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '29',
        viewCount: '17102338',
        thumbnails: 'https://i.ytimg.com/vi/EQwIC0424XQ/default.jpg',
        category: ['TECH'],
        isAd: false,
        channelId: 'UC8C0Yd20ke5XqOiZvMVgM9w',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '204000',
            dailyViewCount: 1255886,
            title: 'Google Play Korea',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLSXktO50BAanBDtrP6_RG7cWVy5CBk5eDyAAvQwAw=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 206,
            channelId: 'UC8C0Yd20ke5XqOiZvMVgM9w',
        },
    },
    {
        videoId: 'ORQd1W9n4TA',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-14T11:35:46Z',
        durationSeconds: 266,
        dislikeCount: '7021',
        description:
            '양배추를 색다른 방법으로 요리했더니 고기보다 맛있어서 놀랐어요\n집에 처치곤란한 양배추가 있다면 만들어 보세요! 양배추 한 통이 순식간에 사라져요\n\n\n➤ 재료 (12개 기준)\n- 양배추 750g\n- 양파 2개 (중간사이즈)\n- 계란 2개\n- 다진마늘 0.5큰술\n- 밀가루 반 컵\n- 소금 1작은술\n- 후추 0.5작은술\n- 타임 1작은술 (선택)\n- 크러쉬드 레드페퍼 또는 고춧가루 1작은술\n- 식용유\n\n[ 요거트 소스 ]\n- 요거트 반 컵\n- 다진마늘 0.5작은술\n- 소금 0.25작은술\n- 레몬즙 0.5큰술\n- 파슬리가루 0.5작은술\n\n\n\n➤ Tips\n1. 매콤한 맛을 원하지 않을 경우, 크러쉬드 레드페퍼(또는 고춧가루)를 생략해주세요\n2. 반죽이 너무 묽을 경우, 밀가루를 1~2큰술 정도 추가해주세요\n3. 요거트소스가 아닌 케찹, 칠리소스 등 원하는 소스를 찍어 먹어도 좋아요\n4. 요거트소스는 미리 만들어서 1시간 냉장보관 후 먹으면 더 맛있어요\n\n\n\n\n▻ Copyright 2021. 하음쿠킹 Haeum Cooking. All rights reserved.\n   ( 영상의 재업로드 및 2차 편집을 금지합니다. )\n\n\n▻ 비즈니스 문의 : unihesuiz@gmail.com\n\n\n\n#양배추요리 #양배추계란 #양배추패티 #간단요리\n#cabbagerecipe #cabbagepatties',
        searchDate: '2021-09-13',
        likeCount: '142724',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 169344,
        title: '양배추를 이렇게 만들었더니 고기보다 맛있어요! 순식간에 양배추 한 통이 사라져요 Cabbage Recipe',
        tags: [
            '양배추요리',
            '양배추전',
            '양배추패티',
            '간단요리',
            '양배추계란',
            'cabbagerecipe',
            'cabbagepatties',
            'vegetarianrecipe',
            'キャベツのレシピ',
            'สูตรกะหล่ำปลี',
            'Receitaderepolho',
            'Recetaderepollo',
            'yt:cc=on',
        ],
        commentCount: '2218',
        duration: 'PT4M26S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '26',
        viewCount: '15947655',
        thumbnails: 'https://i.ytimg.com/vi/ORQd1W9n4TA/default.jpg',
        category: ['FOOD'],
        isAd: false,
        channelId: 'UCWkI9Qcm3vfRY0bZw71ZzYw',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '217000',
            dailyViewCount: 265360,
            title: '하음쿠킹 Haeum Cooking',
            thumbnails:
                'https://yt3.ggpht.com/NH2Vc0GSrHwCPWVaGAYyGalCbULxk8qgzNbCuhOtlNrWWxKIy7O1Hc5nt3KxlodlR0H_hyrB=s800-c-k-c0x00ffffff-no-rj',
            channelId: 'UCWkI9Qcm3vfRY0bZw71ZzYw',
            subscriberChange: 3931,
        },
    },
    {
        videoId: '5G1i4WwgddE',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-19T09:00:02Z',
        durationSeconds: 200,
        dislikeCount: '1104',
        description:
            '▶More information\n\nCRAVITY Official Fan cafe   : http://cafe.daum.net/cravity-official\nCRAVITY Official Twitter      : http://twitter.com/CRAVITYstarship\n                                                 : http://twitter.com/CRAVITY_twt\nCRAVITY Official Facebook : http://facebook.com/OfficialCRAVITY\nCRAVITY Official Weibo       : http://weibo.com/cravity\n\n#CRAVITY #크래비티 #THE_AWAKENING #WRITTEN_IN_THE_STARS #Gas_Pedal',
        searchDate: '2021-09-13',
        likeCount: '134561',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 12694,
        title: "CRAVITY 크래비티 'Gas Pedal' MV",
        forNotEmbeddable: true,
        commentCount: '23302',
        duration: 'PT3M20S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '15360892',
        thumbnails: 'https://i.ytimg.com/vi/5G1i4WwgddE/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UCYDmx2Sfpnaxg488yBpZIGg',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '4810000',
            dailyViewCount: 629773,
            title: 'starshipTV',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLRU23495SJkzAN1qCqMlW2XhqCPfFybbLFR2krS=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 689,
            channelId: 'UCYDmx2Sfpnaxg488yBpZIGg',
        },
    },
    {
        videoId: 'nMLQCrUZ3IY',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-17T13:15:05Z',
        durationSeconds: 852,
        dislikeCount: '23046',
        description:
            '오늘은 오랜만에 블루 음식 먹방 입니다~\n여기 저기 돌면서 파란색 디저트 위주로 싹 모아봤어요!\n오늘 영상도 재밌게 봐주세요^^\n\n시오 구독하기🍒         https://goo.gl/azcgUX \n시오 인스타그램🍒     https://www.instagram.com/sio_yo/ \n비즈니스 문의🍒         kiki_05@naver.com\n구독과 좋아요&댓글은 저에게 큰 힘이 됩니다♥\n\nSIO Subscribe🍒      https://goo.gl/azcgUX\nSIO Instagram🍒      https://www.instagram.com/sio_yo/ \nbusiness mail🍒       kiki_05@naver.com\nThank you for watching! Please Thumbs Up and Subscribe!\n\n🎵 Happy walk by 이세상\nhttps://www.sellbuymusic.com/musicDetail/16176\n\n🎵 밤 마실 - Night Walk by Jae Lee\nhttps://www.sellbuymusic.com/musicDetail/11015\n\n영상에 사용된 음악은 셀바이뮤직에서 무상으로 제공(협찬)받았습니다 \nThe music used in the video was provided free of charge by sellbuymusic.\n映像に使用された音楽は、セルバイミュージックから無償で提供されました。\n\n #ASMR #MUKBANG #galaxy #honey #jelly #honeyJelly #candy #desserts  #Desserts #NoodlesJelly #Ice cream #블루 #파란색음식 #디저트 #KOREANFOOD #아이스크림 #젤리 #먹방 #레시피 #Watermelon',
        searchDate: '2021-09-13',
        likeCount: '181573',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 245011,
        title: 'ASMR MUKBANG | 직접 만든 갤럭시 꿀젤리 블루 디저트 아이스크림 먹방 & 레시피 DESSERT GALAXY HONEY JELLY CANDY',
        forNotEmbeddable: true,
        tags: [
            'sio',
            '시오',
            'asmr sio',
            'asmr시오',
            'yt:cc=on',
            'ASMR',
            'MUKBANG',
            'EATING',
            'EATING SOUND',
            'EATING SHOW',
            '먹방',
            '리얼사운드',
            'korean mukbang',
            'KOREAN FOOD',
            'EAT',
            'galaxy',
            'honeyjelly',
            'honeyJelly',
            'candy',
            'desserts',
            'Desserts',
            'NoodlesJelly',
            'Icecream',
            'Watermelon',
            'Jelly',
            'Strawberry',
            'Tanghulu',
            'Ice cream',
            '꿀젤리',
            '블루푸드',
            '디저트',
            'KOREANFOOD',
            '아이스크림',
            '블루',
            '파란색음식',
            '레시피',
            'food',
            'korean food',
            'Korean cuisine',
            'корейская',
        ],
        commentCount: '5595',
        duration: 'PT14M12S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '22',
        viewCount: '14493558',
        thumbnails: 'https://i.ytimg.com/vi/nMLQCrUZ3IY/default.jpg',
        category: ['ASMR'],
        isAd: false,
        channelId: 'UCRtoqRleHkDQRVgN9OwV6TA',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '5020000',
            dailyViewCount: 3255891,
            title: 'SIO ASMR',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLSn1ug4coRv0Nb7VxpjqrT6Bsomt018FISvdr52rg=s800-c-k-c0x00ffffff-no-rj',
            subscriberChange: 13448,
            channelId: 'UCRtoqRleHkDQRVgN9OwV6TA',
        },
    },
    {
        videoId: 'gCszAvYz1Go',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-27T15:00:21Z',
        durationSeconds: 27,
        dislikeCount: '26418',
        description:
            '#LISA #리사 #BLACKPINK #블랙핑크 #FIRSTSINGLEALBUM #LALISA #VISUAL_TEASER #20210910_12amEST #20210910_1pmKST #RELEASE #YG',
        searchDate: '2021-09-13',
        likeCount: '2067401',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 50260,
        title: 'LISA - FIRST SINGLE ALBUM LALISA VISUAL TEASER #1',
        forNotEmbeddable: true,
        tags: [
            'YG Entertainment',
            'YG',
            '와이지',
            'K-pop',
            'BLACKPINK',
            '블랙핑크',
            '블핑',
            '제니',
            '로제',
            '리사',
            '지수',
            'Lisa',
            'Jisoo',
            'Jennie',
            'Rosé',
            'BLINK',
            '블링크',
            'LISA SOLO',
            'LALISA',
            '리사 솔로',
        ],
        commentCount: '288264',
        duration: 'PT27S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        viewCount: '14001261',
        thumbnails: 'https://i.ytimg.com/vi/gCszAvYz1Go/default.jpg',
        category: ['MUSIC'],
        isAd: false,
        channelId: 'UCOmHUn--16B90oW2L6FRR3A',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '66200000',
            dailyViewCount: 163342245,
            title: 'BLACKPINK',
            thumbnails:
                'https://yt3.ggpht.com/ytc/AKedOLTat8_vr7h2i29n67lvNLMp1F-9Ch2ejFRlRzt0zQ=s800-c-k-c0x00ffffff-no-rj-mo',
            subscriberChange: 72413,
            channelId: 'UCOmHUn--16B90oW2L6FRR3A',
        },
    },
    {
        videoId: '-UroBRG1rY8',
        isOnlyChannelStat: false,
        durationSeconds: 220,
        dislikeCount: '1839',
        description:
            "퍼플키스(PURPLE KISS) 'Zombie' MV\n\nSubscribe 'PURPLE K!SS'\n▶ https://goo.gl/izZq6J\n\nMore about 'PURPLE K!SS'\n▶ Official YT : https://www.youtube.com/c/purplekiss\n▶ Official FB : https://bit.ly/2OEtlQl\n▶ Official IG : https://bit.ly/3le9tCE\n▶ Official TW : https://twitter.com/RBW_PURPLEKISS\n▶ Official V LIVE : https://channels.vlive.tv/9C3C5F/home\n▶ Official Fan Cafe : http://cafe.daum.net/PURPLEKISS\n▶ Official TikTok : https://vt.tiktok.com/ZSJqFaDn3/\n▶ Official Weibo : https://bit.ly/3jfaolr\n\n#퍼플키스 #Zombie #Music_Video\n#PURPLEKISS #퍼플키스\n#박지은 #나고은 #도시 #이레 #유키 #채인 #수안\n#ParkJiEun #NaGoEun #Dosie #Ireh #Yuki #Chaein #SWAN\n\nⓒ 2021 RBW Inc. All Rights Reserved",
        likeCount: '154365',
        nations: ['KR'],
        title: "퍼플키스(PURPLE KISS) 'Zombie' MV",
        forNotEmbeddable: true,
        duration: 'PT3M40S',
        isShorts: false,
        viewCount: '13988928',
        isAd: false,
        channelId: 'UCor8nQnEdMs4eBcU-uVBQ8g',
        publishedAt: '2021-09-08T09:00:09Z',
        category1: '0.9940',
        searchDate: '2021-09-13',
        searchEpoch: 1631509802228,
        dailyViewCount: 1380970,
        tags: [
            '퍼플키스',
            'PURPLE KISS',
            '퍼플키스 박지은',
            '퍼플키스 나고은',
            '퍼플키스 도시',
            '퍼플키스 이레',
            '퍼플키스 유키',
            '퍼플키스 채인',
            '퍼플키스 수안',
            'purple kiss park ji eun',
            'purple kiss na go eun',
            'purple kiss dosie',
            'purple kiss ireh',
            'purple kiss yuki',
            'purple kiss chaein',
            'purple kiss swan',
            'パープルキス',
        ],
        commentCount: '16108',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '10',
        thumbnails: 'https://i.ytimg.com/vi/-UroBRG1rY8/default.jpg',
        category: ['MUSIC'],
        categoryProbs: [
            { category: 'MUSIC', percent: '0.9940' },
            { category: 'ENTN', percent: '0.0020' },
            { category: 'LIFE', percent: '0.0008' },
        ],
        favoriteCount: '0',
        isLive: true,
        channel: {
            subscriberCount: '499000',
            dailyViewCount: 42903,
            title: 'PURPLE KISS',
            thumbnails:
                'https://yt3.ggpht.com/CK4SpTHVh8oGHfMdKBoKUWzket3Pou5GED60mfmtYLnBY0XniVEVObHAvCzK4FNhMwp4Dll7=s800-c-k-c0x00ffffff-no-nd-rj',
            subscriberChange: 1034,
            channelId: 'UCor8nQnEdMs4eBcU-uVBQ8g',
        },
    },
    {
        videoId: 'TJJkZidfSaI',
        isOnlyChannelStat: false,
        publishedAt: '2021-08-27T07:11:42Z',
        durationSeconds: 248,
        dislikeCount: '13344',
        description:
            '어몽어스들이 수학문제를 제대로 풀 수 있을까요?\n발디선생을 만난 어몽어스들 재미있게 봐주세요^^',
        searchDate: '2021-09-13',
        likeCount: '87665',
        searchEpoch: 1631509802228,
        nations: ['KR'],
        dailyViewCount: 980194,
        title: '어몽어스 VS 좀비 애니메이션 9화 AMONG US ANIMATION EP 9',
        tags: [
            '어몽어스',
            '어몽어스 애니메이션',
            'AMONG US',
            '몬스터',
            '좀비',
            '어몽어스좀비',
            'zombie',
            'Peanut',
            'Avengers',
            '탈출',
            "Baldi's Basics Classic",
            'Baldi',
            '발디의 수학교실',
        ],
        commentCount: '1156',
        duration: 'PT4M8S',
        searchTime: '05:10:02',
        isCategoryUpdate: true,
        originalCategory: '1',
        viewCount: '13658730',
        thumbnails: 'https://i.ytimg.com/vi/TJJkZidfSaI/default.jpg',
        category: ['FILM'],
        isAd: false,
        channelId: 'UCT2sZ95FeYWxl7FBf9mreAg',
        favoriteCount: '0',
        isLive: false,
        channel: {
            subscriberCount: '265000',
            dailyViewCount: 3107770,
            title: '땅콩 Peanut',
            thumbnails:
                'https://yt3.ggpht.com/OhWopw8tGDivkpmfBGInzicFEoW456YggHe-Xc2KJGuK7NKsuxO6lTdytZYM84rId5_PcOd7=s800-c-k-c0x00ffffff-no-rj',
            channelId: 'UCT2sZ95FeYWxl7FBf9mreAg',
            subscriberChange: 4448,
        },
    },
],
    

